<hrs3>      ::= <weekly> | <biweekly>
<weekly>    ::= <dayshift-list>
<biweekly>  ::= "B" <biweeks>
<biweeks>   ::= <weekly> | <weekly> "|" <weekly>
<dayshift-list> ::= <days-shifts> "." <dayshift-list> | <days-shifts>
<days-shifts> ::= <dayspec> <timespec>
<dayspec>   ::= <day> | <day> <dayspec> | <day> "-" <day> | <day> "-" <day> <dayspec>
<day>       ::= "M" | "T" | "W" | "R" | "F" | "A" | "U"
<timespec>  ::= <timerange> "&" <timerange> | <timerange>
<timerange> ::= <time> "-" <time>
<time>      ::= <hour> | <hour> <minute>
<hour>      ::= <nor-hour> | <mil-hour>
<minute>    ::= <zero-to-5> <digit>
<year>      ::= <one-to-9> <digit> <digit> <digit>
<one-to-9>  ::= "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9"
<digit>     ::= "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9"
<zero-to-5> ::= "0" | "1" | "2" | "3" | "4" | "5"
<nor-hour>  ::= "0" | "1" | "2" | ... | "23"
<mil-hour>  ::= "00" | "01" | "02" | ... | "23"
