hrs3      = weekly | biweekly ;
weekly    = day-shift-list ;
biweekly  = "B", year, weekly, [ "|", weekly ] ;
day-shift-list = days-shifts, ".", day-shift-list | days-shifts ;
days-shifts = days, { days }, timespec ;
days      = day, { day } | day, "-", day ;
day       = "M" | "T" | "W" | "R" | "F" | "A" | "U" ;
timespec  = timerange, { "&", timerange } ;
timerange = time, "-", time ;
time      = hour, [ minute ] ;
hour      = nor-hour | mil-hour ;
minute    = zero-to-5, digit ;
year      = one-to-9 digit digit digit ;
one-to-9  = "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" ;
digit     = "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" ;
zero-to-5 = "0" | "1" | "2" | "3" | "4" | "5" ;
nor-hour  = "0" | "1" | "2" | ... | "24" ;
mil-hour  = "00" | "01" | "02" | ... | "24" ;
